version: '3.8'

services:
  # LLM Service auf dem Jetson Nano
  llm-server:
    build:
      context: .
      dockerfile: docker/llm-server.Dockerfile
    container_name: llm-server
    runtime: nvidia  # Für GPU-Zugriff
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - MODEL_PATH=deepseek-ai/deepseek-coder-1.3b-base
    ports:
      - "8888:8080"
    volumes:
      - ./models:/app/models
      - ./cache:/app/cache
      - ./config:/app/config
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # Hauptserver mit Orchestrierung
  orchestrator:
    build:
      context: .
      dockerfile: docker/orchestrator.Dockerfile
    container_name: llm-orchestrator
    ports:
      - "9999:8000"
    volumes:
      - ./src:/app/src
      - ./projects:/app/projects
      - ./config:/app/config
    environment:
      - LLM_SERVER_URL=http://192.168.178.36:8888
      - CORS_ORIGINS=["http://localhost:3333"]  # Array von erlaubten Origins
    networks:
      - app-network

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: llm-frontend
    ports:
      - "3333:3000"
    volumes:
      - ./src/ui/frontend:/app
      - /app/node_modules
      - ./config:/app/config
    environment:
      - REACT_APP_API_URL=http://localhost:9999
      - REACT_APP_WS_URL=ws://localhost:9999
      - PORT=3000
    depends_on:
      - orchestrator
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 